### ISSUE TITLE
Backend theme 

### ISSUE THREAD

**Issue by ghermans** [avored/laravel-ecommerce#217]
These tasks should take place during the back-end theme improvements.
 
## Todo

- [x] Deprecate support for the current theme.
- [x] Change datagrids to tables instead divs.
- [x] Fix responsive support (mobile / tablet).
- [ ] Fix summernote or change it with some other Vue WYSIWYG editor.
- [x] Fix form inputs
- [x] Reorder the left side menu options to create a better user experience.

**Comment by indpurvesh** [comment]
@ghermans 

To me seems like you have made big changes in term of design so if you want: You can create another branch `dev/design` and we might merge it later on.

I have added a monthly revenue widget and to do that I have to add `cost_price` field into `products` table so you might have to do after `pull` you might have to do this two command again.

    php artisan avored:install

second

    php artisan avored:admin:make

thanks

**Comment by ghermans** [comment]
@indpurvesh  i created this ticket actually for myself so that i know what i still need todo since i can't add things to the project board.
Regarding creating a new branch: i can't create new branches on the original repo (only to my fork).
Thanks for the feedback regarding the new widget, i have just merged the dev branch with my fork.

**Comment by indpurvesh** [comment]
@ghermans I have added you into a project team.  I hope that then you can manage projects easily. I have created `design` branch too.

**Comment by ghermans** [comment]
@indpurvesh  while trying to push to the design branch i receive the current error 

> $ git push
> ERROR: Permission to avored/laravel-ecommerce.git denied

**Comment by indpurvesh** [comment]
Try it now @ghermans
